name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - run: sudo apt update
    - run: sudo apt install -y libcurl4-openssl-dev curl apt-transport-https ssl-cert ca-certificates gnupg lsb-release 
    - uses: actions/checkout@v4
    - name: Build
      run: cargo build --verbose
    - name: RustFmt
      run: cargo fmt --check
    - name: Clippy
      run: cargo clippy --verbose
    - name: Run tests
      run: cargo test --verbose
